export type PageIdentity = 
| 'main-menu' 
| 'deck-viewer' 
| 'astrological-houses'
| 'calendar' 
| 'practitioners-list'
| 'live-astrology'
| 'card-finder-introduction-part-1'
| 'card-finder-introduction-part-2'
| 'date-selector'
| 'name-entry'
| 'nativety-time-entry'
| 'birth-location-entry'
| 'card-stack'
| 'birthdate-card-stack'
| 'name-card-stack'
| 'growth-card-carousel'
| 'practitioner-view'
| 'inspect'
;